version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code. Syncing if successful.(webhook test bump)
      - npm run build && aws s3 sync build/ s3://integrify-system-build
artifacts:
  files:
    - build/**
