version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building static files for s3 hosting. Syncing if successful.
      - npm run build && aws s3 sync build/ s3://integrify-system-build

