/*eslint-disable */
export const FETCH_USER = 'FETCH_USER';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const ATTENDANCE_LOADING = 'ATTENDANCE_LOADING';
